Update upload-import-sp.yaml

diff --git a/.github/workflows/upload-import-sp.yaml b/.github/workflows/upload-import-sp.yaml
--- a/.github/workflows/upload-import-sp.yaml
+++ b/.github/workflows/upload-import-sp.yaml
@@ -4,9 +4,10 @@ name: site-transfer-agent-coordinator - Download and extract Import zip and uplo
 # Use the issue context to determine import zip (and still allow it as an optional parameter)
 
 env:
-  SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
   SHAREPOINT_TENANT_ID: ${{ secrets.SHAREPOINT_TENANT_ID }}
-  SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
+  AZURE_APP_ID: ${{ env.AZURE_APP_ID }}
+  AZURE_CERTIFICATE_BASE64: ${{ secrets.AZURE_CERTIFICATE_BASE64 }}
+  AZURE_CERTIFICATE_PASSWORD: ${{ secrets.AZURE_CERTIFICATE_PASSWORD }}
 
 on:
   workflow_dispatch:
@@ -36,16 +37,20 @@ jobs:
       - name: Check inputs
         run: |
           npm --version
-          if [ -z "${{ env.SHAREPOINT_CLIENT_SECRET }}" ]; then
-            echo "Error: SHAREPOINT_CLIENT_SECRET is not set."
-            exit 1
-          fi
           if [ -z "${{ env.SHAREPOINT_TENANT_ID }}" ]; then
-            echo "Error: SHAREPOINT_TENANT_ID is not set in the GitHub secrets."
+            echo "Error: SHAREPOINT_TENANT_ID is not set."
             exit 1
           fi
-          if [ -z "${{ env.SHAREPOINT_CLIENT_ID }}" ]; then
-            echo "Error: SHAREPOINT_CLIENT_ID is not set in the GitHub secrets."
+          if [ -z "${{ env.AZURE_APP_ID }}" ]; then
+            echo "Error: AZURE_APP_ID is not set."
+            exit 1
+          fi
+          if [ -z "${{ env.AZURE_CERTIFICATE_BASE64 }}" ]; then
+            echo "Error: AZURE_CERTIFICATE_BASE64 is not set in the GitHub secrets."
+            exit 1
+          fi
+          if [ -z "${{ env.AZURE_CERTIFICATE_PASSWORD }}" ]; then
+            echo "Error: AZURE_CERTIFICATE_PASSWORD is not set in the GitHub secrets."
             exit 1
           fi
           if [ -z "${{ github.event.inputs.zip_url }}" ]; then
@@ -225,8 +230,9 @@ jobs:
       - name: Run SharePoint Upload Action
         id: sharepoint-upload-step
         run: |
-          bash .github/actions/upload-sharepoint/upload-to-sharepoint.sh "${{ env.temp_dir }}/content/docx" "${{ env.FIRST_MP }}" \
-            "${{ env.SHAREPOINT_CLIENT_ID }}" "${{ env.SHAREPOINT_TENANT_ID }}" "${{ env.SHAREPOINT_CLIENT_SECRET }}" \
+          bash .github/actions/upload-sharepoint/upload-to-sharepoint.sh "${{ env.temp_dir }}/content/docx" \
+            "${{ env.FIRST_MP }}" "${{ $SHAREPOINT_TENANT_ID }}" "${{ env.$AZURE_APP_ID }}" \
+            "${{ env.AZURE_CERTIFICATE_BASE64 }}" "${{ env.$AZURE_CERTIFICATE_PASSWORD }}" \
             "${{ github.event.inputs.aemy_callbacks }}" "${{ github.event.inputs.aemy_context }}"
         shell: bash
         #        uses: ./.github/actions/upload-sharepoint
