Update upload-import-sp.yaml

diff --git a/.github/workflows/upload-import-sp.yaml b/.github/workflows/upload-import-sp.yaml
--- a/.github/workflows/upload-import-sp.yaml
+++ b/.github/workflows/upload-import-sp.yaml
@@ -130,20 +130,20 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Read fstab file
-        uses: pietrobolcato/action-read-yaml@1.0.0
-        continue-on-error: true
-        id: read_action_js
+        id: fstab_data
+        uses: jbutcher5/read-yaml@1.6
         with:
-          config: ${{ github.workspace }}/fstab.yaml
+          file: ${{ github.workspace }}/fstab.yaml
+          key-path: '["mountpoints","folders"]'
 
       - name: Set up the mountpoints and folders
         run: |
-          echo ${{ steps.read_action_js.outputs }}
-          mountpoints=${{ steps.read_action_js.outputs['mountpoints'] }} || { echo "FSTab folders were not found. Exiting..."; exit 1; }
+          echo ${{ steps.fstab_data.outputs.data }}
+          mountpoints=${{ steps.read_action_js.outputs.data['mountpoints'] }} || { echo "FSTab mountpoints were not found. Exiting..."; exit 1; }
           echo "mountpoints=${mountpoints}" >> $GITHUB_ENV
           echo "mountpoints ${mountpoints}"
           
-          folders=${{ steps.read_action_js.outputs['folders'] }} || { echo "FSTab folders were not found.  Proceeding."; }
+          mountpoints=${{ steps.read_action_js.outputs.data['folders'] }} || { echo "FSTab folders were not found.  Proceeding."; }
           echo "folders=${folders}" >> $GITHUB_ENV
           echo "folders ${folders}"
 
